== Our work with Repl.it

Ritza produced several tutorials for Repl.it, an online coding platform.
These are beginner to intermediate coding projects that walk the reader
through building a practical mini-solution to a real-world problem. $ca
$ca $ca $ca $ca $ca

They are each independent from each other, but they can also be used
together as a collection as a way for programmers to gain practical
knowledge in several related areas.

=== link:beginner-web-scraping-with-python-and-repl-it[Beginner web scraping with Python and Repl.it]

This is a beginner’s introduction to webscraping where the reader will
be shown how the web works and how HTML is structured and will build a
Python scraper to download specific content from a specific site.

=== link:building-news-word-clouds-using-python-and-repl-it[Building news word clouds using Python and Repl.it]

This can be followed independently of the previous tutorial but assumes
some of the knowledge shared there. The reader will build a web scraper
using the Python Newspaper library to remove extra "`boilerplate`"
content.

=== link:building-a-discord-bot-with-python-and-repl-it[Building a Discord Bot with Python and Repl.it]

Here the reader learns how to build a basic echo bot using the Discord
API. It leaves the reader with a basic bot set up that can be customized
further.

=== link:building-a-discord-bot-with-node-and-repl-it[Building a Discord bot with Node.js and Repl.it]

This is simply a translation of the Python version, but it’s still
recommended for developers to go through both so that they can see the
differences (and similarities) between the languages in a real project.

=== link:creating-and-hosting-a-basic-django-application-with-django-and-repl-it[Creating and hosting a basic web application with Django and Repl.it]

Here the reader learns how to set up a Django project from scratch and
host it with Repl.it.

=== link:building-a-crm-app-with-nodejs-repl-it-and-mongo-db[Building a CRM app with NodeJS, Repl.it, and MongoDB]

In this tutorial the reader builds a CRM (Customer Relationship Manager)
with NodeJS, showing basic crud applications. This is not a translation
of the Django tutorial but many of the same concepts are covered.

=== link:introduction-to-machine-learning-with-python-and-repl-it[Introduction to Machine Learning with Python and repl.it]

Here the reader learns about some basic Machine Learning (text
classification) using Repl.it. This is a high level tutorial showing how
to train a classifier and generate predictions and does not get into the
maths involved.

=== link:quicksort-tutorial-python-implementation-with-line-by-line-explanation[Quicksort tutorial: Python implementation with line by line explanation]

This is the most abstract and theoretical of the collection and shows
the reader how to implement quicksort from sratch. This is more useful
for interview practice or understanding university homework.
