== Don’t try to game writing

Or anything actually.

Everyone wants a shortcut to success. Sometimes they exist. Often they
don’t.

Imagine two people: a writer and a "`growth hacker`".

The writer writes. She writes what she wants to write about. What is
interesting to her. Sometimes it’s only intersting to a few other
people. Sometimes it’s interesting to hundreds of others. Sometimes
millions.

It’s a bit like a lottery. No one can predict whether or not a specific
piece of her writing will be relevant to 100 or 100000 other people, but
they know that after writing a million words, there will be:

* At least 1000 words that she thinks are obviously superior to nearly
all other material they have produced
* 1000 - 10000 words (that don’t necessarily overlap with the above)
that have been read more often than all of the others combined

The growth hacker growth hacks. He spends hours a day looking at keyword
research tools, crafting meta descriptions until they’re just right and
looking for "`gaps`" in the top ranking pages on Google. His only goal
is to write material that gets a lot of views.

Sometimes he writes content himself. More often, he gets lesser mortals
to write on his behalf. Writing is is just manual labour after all. It’s
the growth hacking that is difficult.

After a week, the growth hacker is "`winning`". His content has more
views. More likes. More social shares. After a month, he is winning even
more. The metrics are through the roof. After a year, he is still ahead.

The writer hasn’t looked at any metrics. She doesn’t care. She writes
because she has something inside her; something that she wants someone
else to know. She doesn’t know who her target audience is, or even if
they exist (yet). She just knows that the topic is interesting and
writing about it feels good.

After a month she has two views on her blog. Her grandmother found it
and signed up to receive notifications when new posts are published. She
feels proud.

After six months, she has 30 subscribers. Most of them press "`mark as
read`" when they see emails about her new content. Some of them
unsubscribe.

After a year, she still has far fewer clicks than the growth hacker. He
only thinks about metrics in chunks of 1 million now. To the writer,
every reader is still an inidividual. A reader named Paul wrote to her
to say thanks for the post. It changed his life in some small way. She
likes knowing that there are other Pauls out there who didn’t bother to
tell her, but whose lives were similarly slightly altered.

The growth hacker has got his hockey stick growth. He collects his money
and moves onto another larger project, optimizing again for clicks and
views. And "`engagement`" whatever that means. Usually dodgy Twitter
accounts sharing his content with an automated or semi-automated
sentence attached.

After 5 years, the writer writes The Piece. She doesn’t know it at the
time, but it will always be "`The Piece`" in her mind. The One. It
contains hints of everything else she has ever written. Little pieces of
every idea that has ever crossed her mind. Everyone who reads it knows
that it is unique, that it is good. But they’re not quite sure why.

It gets 5 million views, then 10 million, then 100 million. But she
messed up the Google Analytics snippet that someone told her to install,
so she doesn’t even know.
